FROM tensorrt_llm/devel:latest

COPY third-party/tensorrt-llm /opt/tensorrt-llm

WORKDIR /opt/tensorrt-llm
RUN python3 scripts/build_wheel.py --trt_root /usr/local/tensorrt && \
    pip install build/tensorrt_llm*.whl && \
    python3 scripts/build_wheel.py --clean  --trt_root /usr/local/tensorrt

RUN python -m pip install huggingface_hub

WORKDIR /workspace
