name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
#  pypi:
#    name: Publish release artifact on PyPi repository
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up Python
#        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c  # v4
#        with:
#          python-version: 3.10
#
#      - name: Check out the repo
#        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
#
#      - name: Install dependencies
#        run: |
#          pip install --upgrade pip
#          pip install setuptools wheel
#
#      - run: |
#          python setup.py sdist bdist_wheel
#      - run: |
#          pip install twine
#
#      - name: Upload to PyPi
#        env:
#          OPTIMUM_NVIDIA_PYPI_TOKEN: ${{ secrets.OPTIMUM_NVIDIA_PYPI_TOKEN }}
#        run: |
#          twine upload dist/* -u __token__ -p "$OPTIMUM_NVIDIA_PYPI_TOKEN"

  docker:
    name: Build and push containers to registries
    runs-on:
      group: aws-highmemory-32-plus
    permissions:
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        python-version: ['3.10', '3.12']

    steps:
      - name: Extract inlined Python version
        run: echo "INLINE_PYTHON_VERSION=$(echo ${{ matrix.python-version }} | sed 's/\.//')" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Retrieve TensorRT-LLM dependency
        run:  echo "TENSORRT_LLM_VERSION=$(grep -i 'tensorrt-llm ==' setup.py | cut -c22- | rev | cut -c3- | rev)" >> $GITHUB_ENV

      - name: Print out targeted TensorRT-LLM version
        run: echo "Building against TensorRT-LLM ${{ env.TENSORRT_LLM_VERSION }}"

      - name: Check out TensorRT-LLM repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          path: tensorrt-llm
          repository: nvidia/tensorrt-llm
          submodules: true
          lfs: true
          fetch-depth: 1
          ref: v${{ env.TENSORRT_LLM_VERSION }}

      - name: Build TensorRT-LLM base image
        id: build-tensorrt-llm-base
        run: |
          cd tensorrt-llm
          make -C docker release_build \
            IMAGE_TAG=v${{ env.TENSORRT_LLM_VERSION }}-py${{ matrix.python-version }} \
            CUDA_ARCHS="75-real;80-real;86-real;89-real;90-real" \
            PYTHON_VERSION=${{ matrix.python-version }}

      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Log in to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f  # v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302  # v6.2.0
        with:
          images: huggingface/optimum-nvidia
          tags: |
            type=pep440,pattern={{raw}},suffix=-py${{ env.INLINE_PYTHON_VERSION }}
            type=semver,pattern={{raw}},suffix=-py${{ env.INLINE_PYTHON_VERSION }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a  # v7.3.0
        with:
          context: .
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            TRTLLM_VERSION=${{ env.TENSORRT_LLM_VERSION }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8  # v4.2.2
        with:
          subject-name: huggingface/optimum-nvidia
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true